sudo: required
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
services:
  - docker
install:
  - npm install
script:
  - docker build -t marcdomain/balder-ah-frontend .
  - docker run marcdomain/balder-ah-frontend npm run coverage
deploy:
  provider: elasticbeanstalk
  region: "${AWS_REGION}"
  app: "balder-ah-frontend"
  env: "BalderAhFrontend-env"
  bucket_name: "${BUCKET_NAME}"
  bucket_path: "balder-ah-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: $AWS_SECRET_KEY
